# =========================================
# 🌌 Little Matrix Simulation Configuration
# =========================================

# General Settings
simulation:
  name: "Little Matrix Enhanced Simulation"
  description: "An expansive, highly configurable world where agents interact, evolve, and explore using advanced AI-driven behaviors and environmental dynamics."
  render: true
  timesteps: 10000
  save_state_interval: 50
  llm_metrics_interval: 50
  seed: 42

# Environment Settings
environment:
  grid:
    width: 64                                   # Increased grid size for more exploration
    height: 32
    wrap_around: true
    terrain:
      types:
        - name: "Plains"
          symbol: "."
          movement_cost: 1
          feature_type: "meadow"
          color: [152, 251, 152]               # Lighter green for better visibility
        - name: "Forest"
          symbol: "F"
          movement_cost: 2
          feature_type: "dense_foliage"
          color: [34, 139, 34]
        - name: "Mountain"
          symbol: "^"
          movement_cost: 3
          is_impassable: false
          feature_type: "cliff"
          color: [139, 137, 137]
        - name: "Water"
          symbol: "~"
          movement_cost: 9999
          is_impassable: true
          feature_type: "ocean"
          color: [65, 105, 225]                # Brighter blue for water
      distribution:
        Plains: 40
        Forest: 30
        Mountain: 20
        Water: 10
  resource:
    spawn_rate: 0.2                             # Adjusted spawn rate for more resources
    max_resources: 1000                         # Increased resource cap
    regeneration_rate: 0.02
    types:
      - name: "Food"
        symbol: "*"
        color: [255, 223, 0]                   # Bright yellow for visibility
        spawn_on: ["Plains", "Forest"]
        quantity_range: [20, 50]
      - name: "Water"
        symbol: "~"
        color: [65, 105, 225]
        spawn_on: ["Water"]
        quantity_range: [50, 100]
      - name: "Metal"
        symbol: "M"
        color: [192, 192, 192]
        spawn_on: ["Mountain"]
        quantity_range: [10, 30]
  weather:
    enabled: true
    change_interval: 50
    patterns:
      - name: "Sunny"
        duration_range: [30, 70]
        effects: []
      - name: "Rainy"
        duration_range: [20, 50]
        effects:
          - type: "movement_cost_modifier"
            value: 1.1
          - type: "resource_regeneration_modifier"
            value: 1.2
      - name: "Foggy"
        duration_range: [10, 30]
        effects:
          - type: "visibility_reduction"
            value: 0.5
      - name: "Stormy"
        duration_range: [5, 15]
        effects:
          - type: "movement_cost_modifier"
            value: 1.5
          - type: "agent_energy_cost"
            value: 1.5
          - type: "hazard_spawn_rate"
            value: 0.1
    transitions:
      Sunny:
        Rainy: 0.2
        Foggy: 0.1
        Stormy: 0.05
        Sunny: 0.65
      Rainy:
        Sunny: 0.3
        Foggy: 0.2
        Stormy: 0.1
        Rainy: 0.4
      Foggy:
        Sunny: 0.4
        Rainy: 0.3
        Foggy: 0.2
        Stormy: 0.1
      Stormy:
        Sunny: 0.5
        Rainy: 0.3
        Foggy: 0.1
        Stormy: 0.1

# Agent Settings
agents:
  count: 2                                    # Increased number of agents for more interaction
  perception:
    base_radius: 15                            # Increased perception radius
    modifiers:
      'Explorer': 3
      'Defender': -1
  sight_range:
    base_range: 10
    modifiers:
      'Explorer': 2
      'Gatherer': 0
      'Defender': -2
  behavior:
    initial_energy: 250
    communication_enabled: true
    aggressiveness_base: 0.1
    aggressiveness_modifiers:
      'Defender': 0.2
      'Explorer': 0.05
    energy_consumption_rate: 0.9              # Reduced energy consumption for longer activity
  customization:
    types:
      - name: "Explorer"
        color: [0, 128, 255]
        symbol: "E"
        behavior_traits:
          resource_preference: "knowledge"
          risk_tolerance: 0.8
          speed_modifier: 1.2
          intelligence: 1.5
      - name: "Gatherer"
        color: [255, 215, 0]
        symbol: "G"
        behavior_traits:
          resource_preference: "food"
          risk_tolerance: 0.3
          gathering_efficiency: 1.5
          storage_capacity: 2.0
      - name: "Defender"
        color: [255, 69, 0]                   # Orange-red for better visibility
        symbol: "D"
        behavior_traits:
          protective_instinct: true
          risk_tolerance: 0.6
          combat_skill: 1.5
          armor: 1.2
    status_effects:
      enabled: true
      effects:
        - name: "Poisoned"
          duration: [5, 15]
          health_decrease_per_tick: 2
        - name: "Exhausted"
          duration: [10, 20]
          energy_recovery_modifier: 0.5
        - name: "Inspired"
          duration: [5, 10]
          action_success_modifier: 1.2
    social:
      friendships:
        formation_probability: 0.1           # Increased to encourage social interaction
        decay_rate: 0.005                    # Slower decay
      rivalries:
        formation_probability: 0.05
        aggression_multiplier: 1.5
    learning:
      enabled: true
      methods:
        - name: "Reinforcement Learning"
          parameters:
            learning_rate: 0.1
        - name: "Imitation Learning"
          parameters:
            imitation_probability: 0.2

# Renderer (Pygame) Configuration
renderer:
  display:
    size: [1920, 1080]                       # Full HD resolution
    fps: 60
    fullscreen: false
    resizable: true
  colors:
    background: [25, 25, 112]                # Midnight blue background
    agent_default: [255, 255, 255]
    resource: [0, 155, 127]                  # Spring green for resources
    terrain:
      Plains: [152, 251, 152]
      Forest: [34, 139, 34]
      Mountain: [139, 137, 137]
      Water: [65, 105, 225]
    environment_effects:
      fog: [211, 211, 211, 180]
      rain: [70, 130, 180, 180]
      storm: [123, 104, 238, 150]
  effects:
    show_shadows: true
    particle_effects: true
    weather_effects: true
    smooth_movement: true
    display_hud: true
    show_agent_names: false
    show_health_bars: true
    enable_antialiasing: true               # New option for smoother visuals
    show_grid: true                         # Display grid lines for better orientation
    highlight_selected_agent: true          # Highlight agent when selected

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "simulation.log"
  rotation:
    enabled: true
    max_bytes: 10485760
    backup_count: 5

# Advanced Settings (Optional)
advanced:
  performance:
    max_agent_threads: 16
    tick_rate: 0.05
    use_multiprocessing: true
  experiment_mode:
    enabled: true
    data_collection: true
    save_interval: 50
    data_fields:
      - "agent_positions"
      - "agent_states"
      - "resource_levels"
      - "weather_conditions"
  ai_debugging:
    enabled: false                          # Disabled for better performance
    log_decisions: false
    visualize_decision_trees: false
    profiling:
      enabled: false
      output_file: ""
  compatibility_mode:
    enabled: false
    reduce_graphics: false
    limit_agents: 50
